<%

	// IE and some others are requesting favicon from this location regardless of 
	// tags in HTML.

%><%CODE: 'ACM.ECMA' %>
	{
		// using variable for debug
		var query = context?.query ?? Request.currentRequest;
		var settings = query.settings || {};
		var attributes = query.attributes;
		var skinner = query.attributes.skinner;
		var response = Request.querySkin({
			timeout		: 0,
			verb		: "GET",
			skinner		: skinner,
			resource	: settings.iconLocation || "/$files/favicon.ico",
			parameters	: null,
			attributes	: {
				"User-Agent" : "Local"
			}
		});
		if(response && response.code == 200) {
			// using variable for debug
			var reply = Request.replyBinary( response, {
				'Content-Name' : 'favicon.ico'
			} );
			// now chaining as supposed
			return reply
				.setCode( 200 )
				// .setContentType( "image/x-icon" )
				// .setTimeToLiveWeeks( 60 )
				.setFinal();
		}
	}
	if(false){ // not to be executed 8-)
		import ru.myx.ae3.vfs.Storage;
		// var vfsRoot = skinner.root;
		var vfsRoot = Storage.PUBLIC.relative("resources/skin/skin-standard-html/", null);
		var source = vfsRoot.relative("$files/favicon.ico", null);
		if(source && source.isBinary()){
			// using variable for debug
			var reply = Request.replyBinary( source.binaryContent, {'Content-Name':'favicon.ico'} );
			// now chaining as supposed
			return reply
				.setCode( 200 )
				.setContentType( "image/x-icon" )
				.setTimeToLiveWeeks( 60 )
				.setFinal();
		}
	}
	
	{
		$output( body ) {
			%><!DOCTYPE HTML><%
			%><html><%
				%><head><%
					%><title>404</title><%
				%></head><%
				%><body><%
					%><h1><%
						%>no favicon.ico!<%
					%></h1><%
					%><!-- this message is generated by skin: skin-standard-html --><%
				%></body><%
			%></html><%
		}
		// using variable for debug
		var reply = Request.replyTextual( body, null );
		// now chaining as supposed
		return reply
			.setCode( 404 )
			.setContentType( "text/html" )
			.setTimeToLiveWeeks( 60 )
			.setLastModified( 1000 * 60 * 60 * 24 * 365 )
			.setFinal();
	}
<%/CODE%>