<%

	//	Read: http://www.robotstxt.org/
	//
	//	to specify your own policy override this file (by creating new one) in
	//	you skin implementation.
	//
	
	//
	// Disallows indexing when:
	//	- testing flag specified in response attributes
	//	- 
	//
	
%><%CODE: 'ACM.ECMA' %>
	query = context && context.query || Request.currentRequest;
	attributes = query.attributes;
<%/CODE%><%
%><%FORMAT: 'default' %><%FINAL: 'text/plain' %>
# generated by skin-standard-html

User-Agent: *
Host: <%= query.targetExact %>
<%= attributes.testing ? 'Disallow' : 'Allow' %>: /

<%/FINAL%><%/FORMAT%>
